ELE_MODEL: # element recognition model -- logo only
  WEIGHTS_PATH: models/yolo_nano_320.onnx

SIAMESE_MODEL:
  NUM_CLASSES: 270 # number of brands, users don't need to modify this even the targetlist is expanded
  MATCH_THRE: 0.87 # FIXME: threshold is 0.87 in phish-discovery?
  WEIGHTS_PATH: models/mobilenetv2_64.onnx
  TARGETLIST_PATH: models/expand_targetlist.zip
  DOMAIN_MAP_PATH: models/domain_map.pkl