ELE_MODEL: # element recognition model -- logo only
#  CONFIGS_PATH: train/object_detector/detectron2/configs/faster_rcnn.yaml
#  WEIGHTS_PATH: models/rcnn.pth
  WEIGHTS_PATH: models/yolov10_nano_640.onnx
#  WEIGHTS_PATH: models/yolov10_small_640.onnx
#  WEIGHTS_PATH: models/yolo_middle_640.onnx

SIAMESE_MODEL:
  NUM_CLASSES: 270 # number of brands, users don't need to modify this even the targetlist is expanded
  MATCH_THRE: 0.87 # FIXME: threshold is 0.87 in phish-discovery?
  WEIGHTS_PATH: models/mobilenetv2_128.onnx
#  WEIGHTS_PATH: models/resnetv2_128.onnx
  TARGETLIST_PATH: models/expand_targetlist.zip
  DOMAIN_MAP_PATH: models/domain_map.pkl